on:
  workflow_dispatch: {}
  push:
    paths:
      - '!**.md'
      - '.github/actions/deploy-az-resource/action.yml'
      - '.github/workflows/dev.orchestrator.yml'
      - 'examples/examples.bicep'
      - 'main.bicep'
env:
  ACR_MODULE_N: kv
  RG_N: rg-azure-bicep-key-vault

name: Deploy All Key Vault Examples
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Test Azure Resource Deployment
    - uses: ./.github/actions/deploy-az-resource
      with:
        az_rg_n: ${{ env.RG_N }}

      # Deploy Resource to ACR
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        az bicep build --file main.bicep
        az bicep publish --file main.bicep --target br:${{ secrets.ACR_LOGIN_SERVER }}/bicep/modules/$ACR_MODULE_N:${{ github.sha }}
