on:
  workflow_dispatch: {}
  push:
    paths:
      - '!**.md'
      - '.github/actions/deploy-az-resource/action.yml'
      - '.github/workflows/dev.orchestrator.yml'
      - 'examples/examples.bicep'
      - 'main.bicep'

env:
  ENVIRONMENT: dev
  ACR_MODULE_N: kv
  RG_N: rg-azure-bicep-key-vault
  MAIN_BICEP_FILE_PATH: main.bicep
  TEST_BICEP_FILE_FILE: examples/examples.bicep

name: Deploy All Key Vault Examples
jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo ${{ env.ENVIRONMENT }}
        echo ${{ env.RG_N }}
        echo ${{ env.MAIN_BICEP_FILE_PATH }}
        echo ${{ env.TEST_BICEP_FILE_FILE }}
        echo ${{ env.ACR_MODULE_N }}

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ArtiomLK/commands/.github/workflows/deploy-bicep-module-to-acr.yaml@gh-tempalte-deploy-to-acr
        with:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          RG_N: ${{ env.RG_N }}
          MAIN_BICEP_FILE_PATH: ${{ env.MAIN_BICEP_FILE_PATH }}
          TEST_BICEP_FILE_FILE: ${{ env.TEST_BICEP_FILE_FILE }}
          ACR_MODULE_N: ${{ env.ACR_MODULE_N }}
        secrets:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  # call-workflow-passing-data:
  #   uses: ArtiomLK/commands/.github/workflows/deploy-bicep-module-to-acr.yaml@gh-tempalte-deploy-to-acr
  #   with:
  #     ENVIRONMENT: ${{ env.ENVIRONMENT }}
  #     RG_N: ${{ env.RG_N }}
  #     MAIN_BICEP_FILE_PATH: ${{ env.MAIN_BICEP_FILE_PATH }}
  #     TEST_BICEP_FILE_FILE: ${{ env.TEST_BICEP_FILE_FILE }}
  #     ACR_MODULE_N: ${{ env.ACR_MODULE_N }}
  #   secrets:
  #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  #     ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  #     ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  #     ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}