on:
  workflow_dispatch: {}
  push:
    paths:
      - '!**.md'
      - '.github/actions/deploy-az-resource/action.yml'
      - '.github/workflows/dev.orchestrator.yml'
      - 'examples/examples.bicep'
      - 'main.bicep'
env:
  ACR_MODULE_N: kv
  RG_N: rg-azure-bicep-key-vault

name: Deploy All Key Vault Examples
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code
    - uses: actions/checkout@v3

    #   # Log into Azure
    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    #   # Test Azure Resource Deployment
    # - uses: ./.github/actions/deploy-az-resource
    #   with:
    #     az_rg_n: ${{ env.RG_N }}

    # - name: Build bicep module
    #   uses: Azure/bicep-build-action@v1.0.0
    #   with:
    #     bicepFilePath: main.bicep

    - name: Deploy bicep module to ACR
      uses: ArtiomLK/commands/.github/deploy-to-acr.yaml@gh-tempalte-deploy-to-acr
      with:
        RG_N: ${{ env.RG_N }}