on:
  workflow_dispatch: {}
  push:
    paths:
      - '!**.md'
      - '.github/workflows/kv-public.yml'
      - 'examples/kv-example.bicep'
      - 'main.bicep'
env:
  RG_N: rg-azure-bicep-key-vault-demo

name: Public Key Vault
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Test Azure Resource Deployment
    - name: test-bicep-file-deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RG_N }}
        deploymentMode: Incremental
        template: examples/kv-example.bicep
        failOnStdErr: true